## Question 1: Transpose Array
Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

Example Output:


Transposed Array:
[[1 4]
 [2 5]
 [3 6]]



## Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])

Example Output:

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


## Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Example Output:


Resized Array:
[[1 2 3]
 [4 5 6]
 [7 8 1]]


## Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
Example Output:


Flattened Array:
[1 2 3 4 5 6]


## Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

Example Output:


Transposed Array:
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]



## Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:


arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:

Reshaped Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:


arr_2d = np.array([[1, 2], [3, 4]])

Example Output:

Resized Array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


 ## Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:



arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:


Flattened Array:
[1 2 3 4 5 6 7 8]

In [1]:
import numpy as np

## Question 1: Transpose Array
Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

Example Output:


Transposed Array:
[[1 4]
 [2 5]
 [3 6]]

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Transposed Array: \n",np.transpose(arr_2d))

Transposed Array: 
 [[1 4]
 [2 5]
 [3 6]]


## Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])

Example Output:

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("Reshaped Array: \n",np.reshape(arr_1d,(3,2)))

Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]]


## Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Example Output:


Resized Array:
[[1 2 3]
 [4 5 6]
 [7 8 1]]

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Resized Array: \n",np.resize(arr_1d,(3,3)))

Resized Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 1]]


## Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
Example Output:


Flattened Array:
[1 2 3 4 5 6]

In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Flattened Array: ",np.ndarray.flatten(arr_2d))

Flattened Array:  [1 2 3 4 5 6]



## Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

Example Output:


Transposed Array:
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]

In [9]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("Transposed Array: \n",np.transpose(arr_3d))

Transposed Array: 
 [[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


## Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:


arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:

Reshaped Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [12]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Reshaped Array: \n",np.reshape(arr_1d,(4,3)))

Reshaped Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:


arr_2d = np.array([[1, 2], [3, 4]])

Example Output:

Resized Array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [15]:
arr_2d = np.array([[1, 2], [3, 4]])
print("Resized Array: \n",np.resize(arr_2d,(4,4)))

Resized Array: 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


 ## Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:



arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:


Flattened Array:
[1 2 3 4 5 6 7 8]

In [16]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Flattened Array: ",np.ndarray.flatten(arr_3d))

Flattened Array:  [1 2 3 4 5 6 7 8]
