numpy Slicing

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])

Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])

Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and fourth column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [1]:
import numpy as np

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("First element: ",arr_1d[0])

First element:  1


Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Last three elements: ",arr_1d[-3:])

Last three elements:  [3 4 5]


Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("element at the second row and third column: ",arr_2d[1,2])

element at the second row and third column:  6


Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("the first row: ",arr_2d[0])

the first row:  [1 2 3]


Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("the last column: ",arr_2d[0:3,2])

the last column:  [3 6 9]


Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and fourth column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [10]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
#print(arr_3d)
print("the element at the second matrix, third row, and third column:",arr_3d[1,2,2])

the element at the second matrix, third row, and third column: 18


Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [17]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("the first matrix: \n",arr_3d[0])

the first matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [18]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("the last matrix:\n",arr_3d[-1])

the last matrix:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
